kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kismatic-integration-claim
  annotations:
      volume.beta.kubernetes.io/storage-class: "kismatic-test"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100M
