apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ volume_name }}
  annotations:
    volume.beta.kubernetes.io/storage-class: "kismatic"
spec:
  capacity:
    storage: {{ volume_quota_gb }}Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /{{ volume_name }}
    server: {{ storage_cluster_ip }}
