---
  # YUM
  - name: install transition-etcd yum package
    yum: name=transition-etcd-{{ transition_etcd_yum_version }} state=present
    register: etcd_installation_rpm
    until: etcd_installation_rpm|success
    retries: 3
    delay: 3
    when: ansible_os_family == 'RedHat'

  # DEB
  - name: install transition-etcd deb package
    apt:
      name: transition-etcd={{transition_etcd_apt_version}}
      state: present
      default_release: kismatic-xenial
    register: etcd_installation_deb
    until: etcd_installation_deb|success
    retries: 3
    delay: 3
    when: ansible_os_family == 'Debian'
