---
  # YUM
  - name: install transition-etcd yum package
    yum:
      name: transition-etcd-{{ transition_etcd_yum_version }}
      state: present
      disablerepo: "{{ if package_repository_urls is defined and package_repository_urls != "" }}*{{ end }}"
      enablerepo: "{{ if package_repository_urls is defined and package_repository_urls != "" }}kismatic-*{{ end }}"
    register: etcd_installation_rpm
    until: etcd_installation_rpm|success
    retries: 3
    delay: 3
    when: ansible_os_family == 'RedHat'

  - name: install curl yum package
    yum:
      name: curl
      state: present
      disablerepo: '{% if package_repository_urls is defined and package_repository_urls != "" %}*{% endif %}'
      enablerepo: '{% if package_repository_urls is defined and package_repository_urls != "" %}kismatic-*{% endif %}'
    register: etcd_installation_rpm
    until: etcd_installation_rpm|success
    retries: 3
    delay: 3
    when: ansible_os_family == 'RedHat'

  # DEB
  - name: install transition-etcd deb package
    apt:
      name: transition-etcd={{transition_etcd_apt_version}}
      state: present
      allow_unauthenticated: '{% if package_repository_urls is defined and package_repository_urls != "" %}yes{% else %}no{% endif %}'
      default_release: kismatic-xenial
    register: etcd_installation_deb
    until: etcd_installation_deb|success
    retries: 3
    delay: 3
    when: ansible_os_family == 'Debian'

  - name: install curl deb package
    apt:
      name: curl
      allow_unauthenticated: '{% if package_repository_urls is defined and package_repository_urls != "" %}yes{% else %}no{% endif %}'
      state: present
    register: etcd_installation_deb
    until: etcd_installation_deb|success
    retries: 3
    delay: 3
    when: ansible_os_family == 'Debian'
