---
  - name: download kube-controller-manager image
    command: docker pull gcr.io/google-containers/kube-controller-manager-amd64:{{ kubernetes_version }}

  - name: copy kube-controller-manager.yaml manifest
    template:
      src: kube-controller-manager.yaml
      dest: /etc/kubernetes/manifests/kube-controller-manager.yaml
      owner: "{{ kubernetes_owner }}"
      group: "{{ kubernetes_group }}"
      mode: "{{ kubernetes_service_mode }}"
