---
  - name: install glusterfs yum package
    yum:
      name: glusterfs-server{{glusterfs_server_version}}
      state: present
      disablerepo: '{% if package_repository_urls is defined and package_repository_urls != "" %}*{% endif %}'
      enablerepo: '{% if package_repository_urls is defined and package_repository_urls != "" %}kismatic-*{% endif %}'
      disable_gpg_check: yes
    register: etcd_installation_rpm
    until: etcd_installation_rpm|success
    retries: 3
    delay: 3
    when: ansible_os_family == 'RedHat'

  - name: install glusterfs deb package
    apt:
      name: glusterfs-server{{glusterfs_server_version}}
      state: present
      default_release: kismatic-xenial
    register: etcd_installation_deb
    until: etcd_installation_deb|success
    retries: 3
    delay: 3
    when: ansible_os_family == 'Debian'
