---
  - name: install glusterfs-server package
    package:
      name: "glusterfs-server{{glusterfs_server_version}}"
      state: present
    register: result
    until: result|success
    retries: 3
    delay: 3
