---
  - name: reload services
    command: systemctl daemon-reload
  - name: enable kube-apiserver
    command: systemctl enable kube-apiserver.service
  - name: restart kube-apiserver service
    service:
      name: kube-apiserver.service
      state: restarted
      enabled: yes
  - name: verify kube-apiserver is running
    command: systemctl status kube-apiserver
    register: running
    until: running|success
    retries: 3
    delay: 5
