---
  # YUM repo
  - name: ping Kismatic yum repository
    uri: url="{{ yum_gpg_key_url }}"
    notify:
      - add Kismatic yum repository
      - clean Kismatic yum cache # required to get new versions of packagess
    when: ansible_os_family == 'RedHat'
    ignore_errors: yes
    register: result
    until: "result.status is defined and result.status == 200"
    retries: 3
    delay: 1
    changed_when: "result.status is defined and result.status == 200"

  # DEB repo
  - name: ping Kismatic deb repository
    uri: url="{{ deb_gpg_key_url }}"
    notify:
      - install apt-transport-https package
      - add Kismatic deb key
      - add Kismatic deb repository
      - apt-get update
    when: ansible_os_family == 'Debian'
    ignore_errors: yes
    register: result
    until: "result.status is defined and result.status == 200"
    retries: 3
    delay: 1
    changed_when: "result.status is defined and result.status == 200"

  - meta: flush_handlers  #Run handlers

  # install packages
  - name: install yum packages
    command: /bin/true
    notify:
      - install etcd yum package
      - install kubernetes master yum package
      - install kubernetes node yum package
    when: ansible_os_family == 'RedHat'

  - name: install deb packages
    command: /bin/true
    notify:
      - install etcd deb package
      - install docker-engine deb package
      - install kubernetes networking deb package
      - install kubernetes node deb package
      - install kubernetes master deb package
    when: ansible_os_family == 'Debian'
