---
  # install and start etcd service
  - name: copy etcd.service to remote
    template:
      src: "etcd.service"
      dest: "{{ init_system_dir }}/{{ etcd_service_name }}"
      owner: "{{ etcd_service_owner }}"
      group: "{{ etcd_service_group }}"
      mode: "{{ etcd_service_mode }}"
    notify:
      - reload services
      - restart etcd service

  - name: get etcd server version
    command: curl --cert {{ etcd_certificates_cert_file }} --key {{ etcd_certificates_key_file }} --cacert {{ etcd_certificates_ca_file }} https://127.0.0.1:{{ etcd_service_client_port }}/version
    register: etcd_version
    when: upgrading is defined and upgrading|bool == true

  - name: check if etcd needs to be upgraded
    set_fact:
      etcd_needs_upgrade: "{{ (etcd_version.stdout | from_json)['etcdserver'] != etcd_version }}"
    when: upgrading is defined and upgrading|bool == true

  # force_etcd_restart=true to force restart
  - name: force restart {{etcd_install_bin_name }} service
    command: /bin/true
    notify:
      - restart etcd service
    when: >
      (force_etcd_restart is defined and force_etcd_restart|bool == true) or
      ((etcd_installation_rpm is defined and etcd_installation_rpm.changed == true or etcd_installation_deb is defined and etcd_installation_deb.changed == true) and
      (upgrading is defined and upgrading|bool == true) and
      (etcd_needs_upgrade is defined and etcd_needs_upgrade|bool == true ))

  - meta: flush_handlers  #Run handlers

    #TODO don't use a timeout
  - name: wait for {{ etcd_install_bin_name }} node to be ready after upgrade
    pause: seconds=15
    when: >
      (force_etcd_restart is defined and force_etcd_restart|bool == true) or
      ((etcd_installation_rpm is defined and etcd_installation_rpm.changed == true or etcd_installation_deb is defined and etcd_installation_deb.changed == true) and
      (upgrading is defined and upgrading|bool == true) and
      (etcd_needs_upgrade is defined and etcd_needs_upgrade|bool == true ))

  - name: verify {{ etcd_install_bin_name }} is running
    command: systemctl status {{ etcd_service_name }}
    register: running
    until: running|success
    retries: 3
    delay: 5

  # test etcd
  - name: verify {{ etcd_install_bin_name }} cluster health
    command: "{{ bin_dir }}/{{ etcdctl_install_bin_name }} --endpoint='https://127.0.0.1:{{ etcd_service_client_port }}/' --cert-file={{ etcd_certificates_cert_file }} --key-file={{ etcd_certificates_key_file }} --ca-file={{ etcd_certificates_ca_file }} cluster-health"
    register: result
    until: result|success
    retries: 3
    delay: 5
