---
  - name: download kube-proxy image
    command: docker pull gcr.io/google-containers/kube-proxy-amd64:{{ kubernetes_version }}

  - name: copy kube-proxy.yaml manifest
    template:
      src: kube-proxy.yaml
      dest: /etc/kubernetes/manifests/kube-proxy.yaml
      owner: "{{ kubernetes_owner }}"
      group: "{{ kubernetes_group }}"
      mode: "{{ kubernetes_service_mode }}"
