---
  # setup directories
  - name: create {{ docker_install_dir }}
    file:
      path: "{{ docker_install_dir }}"
      state: directory
  # copy certificates
  - name: copy {{ docker_certificates_cert_file_name }}
    copy:
      src: "{{ tls_directory }}/docker-registry.pem"
      dest: "{{ docker_certificates_cert_path }}"
      owner: "{{ docker_certificates_owner }}"
      group: "{{ docker_certificates_group }}"
      mode: "{{ docker_certificate_mode }}"
  - name: copy {{ docker_certificates_key_file_name }}
    copy:
      src: "{{ tls_directory }}/docker-registry-key.pem"
      dest: "{{ docker_certificates_key_path }}"
      owner: "{{ docker_certificates_owner }}"
      group: "{{ docker_certificates_group }}"
      mode: "{{ docker_certificate_mode }}"
