---
    # remove YUM packages
  - name: remove kismatic-kubernetes-master package
    package: name=kismatic-kubernetes-master state=absent
    when: "'master' in group_names"
    register: result
    until: result|success
    retries: 1
    delay: 1

  - name: remove kismatic-kubernetes-node package
    package: name=kismatic-kubernetes-node state=absent
    when: "'master' in group_names or 'worker' in group_names or 'ingress' in group_names or 'storage' in group_names"
    register: result
    until: result|success
    retries: 1
    delay: 1

  - name: remove kismatic-docker-engine package
    package: name=kismatic-docker-engine state=absent
    when: "'master' in group_names or 'worker' in group_names or 'ingress' in group_names or 'storage' in group_names"
    register: result
    until: result|success
    retries: 1
    delay: 1

  - name: remove kismatic-etcd package
    package: name=kismatic-etcd state=absent
    when: "'etcd' in group_names"
    register: result
    until: result|success
    retries: 1
    delay: 1

  - name: remove etcd package
    package: name=etcd state=absent
    when: "'etcd' in group_names"
    register: result
    until: result|success
    retries: 1
    delay: 1
