apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: gcr.io/google-containers/kube-proxy-amd64:{{ kubernetes_version }}
    command:
      - kube-proxy
      - --hostname-override={{ inventory_hostname }}
      - --kubeconfig={{ kubernetes_kubeconfig_path }}
      - --master={{ kubernetes_master_ip }}
      - --proxy-mode=iptables
      - --v=2
    securityContext:
      privileged: true
    volumeMounts:
      - mountPath: /etc/ssl/certs
        name: "ssl-certs"
      - mountPath: "{{ kubernetes_kubeconfig_path }}"
        name: "kubeconfig"
        readOnly: true
      - mountPath: /etc/kubernetes
        name: "etc-kube-ssl"
        readOnly: true
  volumes:
    - name: "ssl-certs"
      hostPath:
        path: "/usr/share/ca-certificates"
    - name: "kubeconfig"
      hostPath:
        path: "{{ kubernetes_kubeconfig_path }}"
    - name: "etc-kube-ssl"
      hostPath:
        path: "/etc/kubernetes"
