---
  - name: copy Kuberang to node
    copy:
      src: "{{ kuberang_path }}"
      dest: "{{ bin_dir }}/kuberang"
      mode: 0744
  - name: run smoke test checks using Kuberang
    command: "echo smoke test completed"
