---
  # setup directories
  - name: create directory
    file:
      path: "{{ etcd_install_dir }}"
      state: directory
  
  - name: copy CA certificate
    copy:
      src: "{{ tls_directory }}/ca.pem"
      dest: "{{ etcd_certificates_ca_file }}"
      owner: "{{ etcd_certificates_owner }}"
      group: "{{ etcd_certificates_group }}"
      mode: "{{ etcd_certificates_mode }}"
  
  - name: copy etcd server certificate and key
    copy:
      src: "{{ tls_directory }}/{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ etcd_certificates_owner }}"
      group: "{{ etcd_certificates_group }}"
      mode: "{{ etcd_certificates_mode }}"
    when: "'etcd' in group_names"
    with_items:
      - {'src': "{{ inventory_hostname }}-etcd.pem", dest: "{{ etcd_certificates_cert_file }}"}
      - {'src': "{{ inventory_hostname }}-etcd-key.pem", dest: "{{ etcd_certificates_key_file }}"}
