---
  # kubelet
  - name: copy kubelet.service to remote
    template:
      src: kubelet.service
      dest: "{{ init_system_dir }}/kubelet.service"
      owner: "{{ kubernetes_owner }}"
      group: "{{ kubernetes_group }}"
      mode: "{{ kubernetes_service_mode }}"
    notify:
      - reload services
      - restart kubelet service

  - meta: flush_handlers  #Run handlers

  # force_kubelet_restart=true to force restart
  - name: force restart kubelet
    command: systemctl restart kubelet.service
    when: force_kubelet_restart is defined and force_kubelet_restart|bool == true

  - name: verify kubelet is running
    command: systemctl status kubelet
    register: running
    until: running|success
    retries: 3
    delay: 5
