---
  ## Configure a calico pool for the nodes. We need to configure calico
  ## before starting calico-node on the nodes due to
  ## https://github.com/projectcalico/calico-containers/issues/716

  # Two networking modes are supported: 'routed' and 'overlay'. Depending on the mode
  # the pool flags change. Mainly, --ipip is added when 'overlay' is specified.

  - name: create /etc/calico directory
    file:
      path: "{{ calico_dir }}"
      state: directory
  - name: copy calicoctl.cfg to remote
    template:
      src: calicoctl.cfg.j2
      dest: "{{ calicoctl_conf_path }}"
      owner: "{{ kubernetes_owner }}"
      group: "{{ kubernetes_group }}"
      mode: "{{ network_environment_mode }}"
  - name: copy ip-pool.yaml to remote
    template:
      src: ip-pool.yaml.j2
      dest: "{{ calico_ippool_path }}"
      owner: "{{ kubernetes_owner }}"
      group: "{{ kubernetes_group }}"
      mode: "{{ network_environment_mode }}"
  - name: add pods CIDR - {{ kubernetes_pods_cidr }}
    command: calicoctl apply -f {{ calico_ippool_path }}
    run_once: true

  ## Start calico-node serivce on the nodes after configuring the calico pool.
  - name: create {{ network_plugin_dir }} directory
    file:
      path: "{{ network_plugin_dir }}"
      state: directory
  - name: copy 10-calico.conf to remote
    template:
      src: 10-calico.conf.j2
      dest: "{{ network_plugin_dir }}/10-calico.conf"
  - name: copy calico-node.service to remote
    template:
      src: calico-node.service.j2
      dest: "{{ kubernetes_service_dir }}/calico-node.service"
      owner: "{{ kubernetes_owner }}"
      group: "{{ kubernetes_group }}"
      mode: "{{ kubernetes_service_mode }}"
    notify:
      - reload services
      - enable calico-node
      - restart calico-node service
      - verify calico-node is running
  # force_calico_node_restart=true to force restart
  - name: force restart calico-node
    command: /bin/true
    notify:
      - enable calico-node
      - restart calico-node service
      - verify calico-node is running
    when: force_calico_node_restart is defined and force_calico_node_restart|bool == true

  - meta: flush_handlers  #Run handlers
