---
  - name: download networking images
    command: docker pull {{ item }}
    with_items:
      - "{{ calico_node_img }}"
      - "{{ calico_cni_img }}"
      - "{{ calico_ctl_img }}"

  - name: create /etc/calico directory
    file:
      path: "{{ calico_dir }}"
      state: directory

  - name: copy calicoctl.cfg to remote
    template:
      src: calicoctl.cfg.j2
      dest: "{{ calicoctl_conf_path }}"
      owner: "{{ kubernetes_owner }}"
      group: "{{ kubernetes_group }}"
      mode: "{{ network_environment_mode }}"

  - name: copy calico.yaml to remote
    template:
      src: calico.yaml
      dest: /etc/calico/calico.yaml
      owner: "{{ kubernetes_owner }}"
      group: "{{ kubernetes_group }}"
      mode: "{{ kubernetes_service_mode }}"
    when: "inventory_hostname == groups['master'][0]"

  - name: wait until kube-apiserver is up
    command: kubectl get pods --namespace kube-system -l component=kube-apiserver
    register: out
    until: out|success
    retries: 20
    delay: 6
    when: "inventory_hostname == groups['master'][0]"

  - name: start calico containers
    command: kubectl apply -f /etc/calico/calico.yaml
    run_once: true
    when: "inventory_hostname == groups['master'][0]"
