---
  - name: create /etc/calico directory
    file:
      path: "{{ calico_dir }}"
      state: directory

  - name: copy calicoctl.cfg to remote
    template:
      src: calicoctl.cfg.j2
      dest: "{{ calicoctl_conf_path }}"
      owner: "{{ kubernetes_owner }}"
      group: "{{ kubernetes_group }}"
      mode: "{{ network_environment_mode }}"

  - name: copy calico.yaml manifest
    template:
      src: calico.yaml
      dest: /etc/calico/calico.yaml
      owner: "{{ kubernetes_owner }}"
      group: "{{ kubernetes_group }}"
      mode: "{{ kubernetes_service_mode }}"

  # TODO check/wait for k8s controlplane to be up
  #kubectl get pods kube-apiserver-ip-10-0-3-58 --namespace kube-system -o jsonpath='{.status.phase}'
  - name: run calico containers
    command: kubectl apply -f /etc/calico/calico.yaml
    run_once: true
    register: result
    until: result|success
    retries: 10
    delay: 6
