---
  # install YUM packages
  - name: install etcd yum package
    yum: name=kismatic-etcd-{{ kismatic_yum_version }} state=present
    when: "'etcd' in group_names"
    register: result
    until: result|success
    retries: 3
    delay: 3

  - name: install docker yum package
    yum: name=docker state=present
    when: "'worker' in group_names or 'ingress' in group_names or 'storage' in group_names or 'master' in group_names"
    register: result
    until: result|success
    retries: 3
    delay: 3

  - name: install kubelet yum package
    yum: name=kismatic-kubelet state=present
    when: "'worker' in group_names or 'ingress' in group_names or 'storage' in group_names or 'master' in group_names"
    register: result
    until: result|success
    retries: 3
    delay: 3

  - name: install kubectl yum package
    yum: name=kismatic-kubectl state=present
    when: "'master' in group_names"
    register: result
    until: result|success
    retries: 3
    delay: 3

  # install DEB packages
  - name: install etcd deb package
    apt: name=kismatic-etcd={{ kismatic_apt_version }} state=present
    when: "'etcd' in group_names"
    register: result
    until: result|success
    retries: 3
    delay: 3

  - name: install docker deb package
    apt: name=docker.io state=present
    when: "'worker' in group_names or 'ingress' in group_names or 'storage' in group_names or 'master' in group_names"
    register: result
    until: result|success
    retries: 3
    delay: 3

  - name: install kubelet deb package
    apt: name=kismatic-kubelet state=present
    when: "'worker' in group_names or 'ingress' in group_names or 'storage' in group_names or 'master' in group_names"
    register: result
    until: result|success
    retries: 3
    delay: 3

  - name: install kubectl deb package
    apt: name=kismatic-kubectl state=present
    when: "'master' in group_names"
    register: result
    until: result|success
    retries: 3
    delay: 3
