---
  # install YUM packages
  - name: install etcd yum package
    yum: name=etcd-{{ etcd_yum_version }} state=present
    when: "'etcd' in group_names"
    register: result
    until: result|success
    retries: 3
    delay: 3

  - name: install docker-engine yum package
    yum: name=docker-engine-{{ docker_engine_yum_version }} state=present
    when: "'worker' in group_names or 'ingress' in group_names or 'storage' in group_names or 'master' in group_names"
    register: result
    until: result|success
    retries: 3
    delay: 3

  - name: install kubelet yum package
    yum: name=kubelet-{{ kismatic_yum_version }} state=present
    when: "'worker' in group_names or 'ingress' in group_names or 'storage' in group_names or 'master' in group_names"
    register: result
    until: result|success
    retries: 3
    delay: 3

  - name: install kubectl yum package
    yum: name=kubectl-{{ kismatic_yum_version }} state=present
    when: "'master' in group_names"
    register: result
    until: result|success
    retries: 3
    delay: 3

  # install DEB packages
  - name: install etcd deb package
    apt: name=etcd={{ etcd_apt_version }} state=present default_release=kismatic-xenial
    when: "'etcd' in group_names"
    register: result
    until: result|success
    retries: 3
    delay: 3

  - name: install docker-engine deb package
    apt: name=docker-engine={{ docker_engine_apt_version }} state=present default_release=kismatic-xenial
    when: "'worker' in group_names or 'ingress' in group_names or 'storage' in group_names or 'master' in group_names"
    register: result
    until: result|success
    retries: 3
    delay: 3

  - name: install kubelet deb package
    apt: name=kubelet={{ kismatic_apt_version }} state=present default_release=kismatic-xenial
    when: "'worker' in group_names or 'ingress' in group_names or 'storage' in group_names or 'master' in group_names"
    register: result
    until: result|success
    retries: 3
    delay: 3

  - name: install kubectl deb package
    apt: name=kubectl={{ kismatic_apt_version }} state=present default_release=kismatic-xenial
    when: "'master' in group_names"
    register: result
    until: result|success
    retries: 3
    delay: 3
