---
# install YUM packages
  - name: install etcd yum package
    yum: name=kismatic-etcd-{{ kismatic_yum_version }} state=present
    when: "'etcd' in group_names"
    register: result
    until: result|success
    retries: 3
    delay: 3

  - name: install kubernetes master yum package
    yum: name=kismatic-kubernetes-master-{{ kismatic_yum_version }} state=present
    when: "'master' in group_names"
    register: result
    until: result|success
    retries: 3
    delay: 3

  - name: install kubernetes node yum package
    yum: name=kismatic-kubernetes-node-{{ kismatic_yum_version }} state=present
    when: "('worker' in group_names or 'ingress' in group_names or 'storage' in group_names) and 'master' not in group_names"
    register: result
    until: result|success
    retries: 3
    delay: 3

  # install DEB packages
  - name: install etcd deb package
    apt: name=kismatic-etcd={{ kismatic_apt_version }} state=present
    when: "'etcd' in group_names"
    register: result
    until: result|success
    retries: 3
    delay: 3

  - name: install docker-engine deb package
    apt: name=kismatic-docker-engine={{ kismatic_docker_engine_apt_version }} state=present
    when: "'master' in group_names or 'worker' in group_names or 'ingress' in group_names or 'storage' in group_names"
    register: result
    until: result|success
    retries: 3
    delay: 3

  - name: install kubernetes networking deb package
    apt: name=kismatic-kubernetes-networking={{ kismatic_apt_version }} state=present
    when: "'master' in group_names or 'worker' in group_names or 'ingress' in group_names or 'storage' in group_names"
    register: result
    until: result|success
    retries: 3
    delay: 3

  - name: install kubernetes node deb package
    apt: name=kismatic-kubernetes-node={{ kismatic_apt_version }} state=present
    when: "'master' in group_names or 'worker' in group_names or 'ingress' in group_names or 'storage' in group_names"
    register: result
    until: result|success
    retries: 3
    delay: 3

  - name: install kubernetes master deb package
    apt: name=kismatic-kubernetes-master={{ kismatic_apt_version }} state=present
    when: "'master' in group_names"
    register: result
    until: result|success
    retries: 3
    delay: 3
