---
  # YUM
  - name: install etcd yum package
    yum:
      name: etcd-{{ etcd_yum_version }}
      state: present
      disablerepo: '{% if package_repository_urls is defined and package_repository_urls != "" %}*{% endif %}'
      enablerepo: '{% if package_repository_urls is defined and package_repository_urls != "" %}kismatic-*{% endif %}'
    register: etcd_installation_rpm
    until: etcd_installation_rpm|success
    retries: 3
    delay: 3
    when: ansible_os_family == 'RedHat'

  - name: install curl yum package
    yum:
      name: curl
      state: present
      disablerepo: '{% if package_repository_urls is defined and package_repository_urls != "" %}*{% endif %}'
      enablerepo: '{% if package_repository_urls is defined and package_repository_urls != "" %}kismatic-*{% endif %}'
    register: curl_installation_rpm
    until: curl_installation_rpm|success
    retries: 3
    delay: 3
    when: ansible_os_family == 'RedHat'

  # DEB
  - name: install etcd deb package
    apt:
      name: etcd={{etcd_apt_version}}
      state: present
      allow_unauthenticated: '{% if package_repository_urls is defined and package_repository_urls != "" %}yes{% else %}no{% endif %}'
      default_release: kismatic-xenial
    register: etcd_installation_deb
    until: etcd_installation_deb|success
    retries: 3
    delay: 3
    when: ansible_os_family == 'Debian'

  # required until https://github.com/ansible/ansible/issues/14804
  - name: install curl deb package
    apt:
      name: curl
      allow_unauthenticated: '{% if package_repository_urls is defined and package_repository_urls != "" %}yes{% else %}no{% endif %}'
      state: present
    register: curl_installation_deb
    until: curl_installation_deb|success
    retries: 3
    delay: 3
    when: ansible_os_family == 'Debian'
