apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calico-policy-controller
  namespace: kube-system
  labels:
    tier: control-plane
    k8s-app: calico-policy-controller
  annotations:
    kismatic/version: "{{ kismatic_short_version }}"
spec:
  # The policy controller can only have a single active instance.
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: calico-policy-controller
      namespace: kube-system
      labels:
        tier: control-plane
        k8s-app: calico-policy-controller
        kismaticVersion: "{{ kismatic_short_version }}"
    spec:
      # The policy controller must run in the host network namespace so that
      # it isn't governed by policy that would prevent it from working.
      hostNetwork: true
      volumes:
        - name: "ca"
          hostPath:
            path: "{{kubernetes_certificates_ca_path}}"
        - name: "cert"
          hostPath:
            path: "{{kubernetes_certificates_cert_path}}"
        - name: "key"
          hostPath:
            path: "{{kubernetes_certificates_key_path}}"
      containers:
        - name: calico-policy-controller
          image: {{ calico_kube_policy_controller_img }}
          volumeMounts:
            - mountPath: "{{kubernetes_certificates_ca_path}}"
              name: "ca"
            - mountPath: "{{kubernetes_certificates_cert_path}}"
              name: "cert"
            - mountPath: "{{kubernetes_certificates_key_path}}"
              name: "key"
          env:
            # The location of the Calico etcd cluster.
            - name: ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_endpoints
            # Location of the CA certificate for etcd.
            - name: ETCD_CA_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_ca
            # Location of the client certificate for etcd.
            - name: ETCD_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_cert
            # Location of the client key for etcd.
            - name: ETCD_KEY_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_key
            # The location of the Kubernetes API.  Use the default Kubernetes
            # service for API access.
            - name: K8S_API
              value: "{{ kubernetes_master_ip }}"
            - name: CONFIGURE_ETC_HOSTS
              value: "true"
