---
  - hosts: master[0]
    any_errors_fatal: true
    name: "{{ play_name | default('Configure Calico Network Policy') }}"
    remote_user: root
    become_method: sudo
    run_once: true

    roles:
      - addon-network-policy
