---
  - hosts: master[0]
    any_errors_fatal: true
    name: "{{ play_name | default('Configure Calico Network Policy') }}"
    remote_user: root
    become_method: sudo
    run_once: true

    roles:
      - addon-network-policy

    post_tasks:
      - name: remove old calico-policy replication controller if exists
        command: kubectl delete rc calico-policy -n kube-system
        failed_when: false
        when: upgrading is defined and upgrading|bool == true
