---
  - hosts: master:worker:ingress:storage
    any_errors_fatal: true
    name: "Deploy Cluster Certificates"
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml

    roles:
      - role: etcd-cert
        etcd_install_dir: "/etc/etcd_k8s"
      - role: etcd-cert
        etcd_install_dir: "/etc/etcd_networking"
      - kubenode-cert
      - role: docker-registry-container-cert
        when: deploy_internal_docker_registry is defined and deploy_internal_docker_registry|bool == true
      - role: docker-registry-cert
        when: confgiure_docker_with_private_registry is defined and confgiure_docker_with_private_registry|bool == true
