---
  - hosts: master:worker:ingress:storage
    any_errors_fatal: true
    name: "Deploy Cluster Certificates"
    become: yes
    vars_files:
      - group_vars/all.yaml

    roles:
      - kubenode-cert
      - role: docker-registry-container-cert
        when: deploy_internal_docker_registry is defined and deploy_internal_docker_registry|bool == true
