---
  - hosts: master[0]
    name: "{{ play_name | default('Configure Internal Docker Registry') }}"
    remote_user: root
    become_method: sudo
    run_once: true

    roles:
      - role: packages-offline
        when: allow_package_installation|bool == true and disconnected_installation|bool == true and seed_registry|bool == true # install when allowed to install and disconnected
      - role: docker-registry-container
        when: deploy_internal_docker_registry|bool == true and (upgrading is not defined or upgrading|bool == false) # setup a registry running on master[0]
      - role: docker-registry-images
        when: configure_docker_with_private_registry|bool == true and disconnected_installation|bool == true and seed_registry|bool == true # load docker images into the registry
