---
  - hosts: master[0]
    name: "{{ play_name | default('Configure Internal Docker Registry ') }}"
    remote_user: root
    become_method: sudo
    run_once: true

    roles:
      - role: docker-registry-container
