---
  - hosts: master[0]
    name: Load Docker Images Into Private Registry
    remote_user: root
    become_method: sudo
    run_once: true

    roles:
      - role: packages-offline
        when: allow_package_installation|bool == true and disconnected_installation|bool == true
      - role: docker-registry-images
