---
  - hosts: etcd
    any_errors_fatal: true
    name: "Start Kubernetes Etcd Cluster"
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml
      - group_vars/etcd-k8s.yaml

    roles:
      - etcd-cert
      - etcd
