---
  - hosts: etcd
    any_errors_fatal: true
    name: "Start Network Etcd Cluster"
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml
      - group_vars/etcd-networking.yaml

    roles:
      - etcd-cert
      - etcd
