---
  - hosts: master[0]
    any_errors_fatal: true
    name: "{{ play_name | default('Start Kubernetes DNS') }}"
    remote_user: root
    become_method: sudo
    run_once: true

    roles:
      - kube-dns

    post_tasks:
      - name: remove old kube-dns replication controller if exists
        command: kubectl delete rc kube-dns kube-dns-v18 kube-dns-v19 -n kube-system --now --ignore-not-found
        failed_when: false
        when: upgrading is defined and upgrading|bool == true
