---
  - hosts: master
    any_errors_fatal: true
    name: "{{ play_name | default('Start Kubernetes Controller Manager') }}"
    serial: "{{ serial_count | default('100%') }}"
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml

    pre_tasks:
      - name: check if kube-controller-manager service is active
        command: systemctl is-active -q kube-controller-manager.service
        register: status
        failed_when: status.rc !=0 and status.rc != 3
        when: upgrading is defined and upgrading|bool == true

      - name: stop kube-controller-manager service
        service:
          name: kube-controller-manager.service
          state: stopped
          enabled: no
        when: upgrading is defined and upgrading|bool == true and status is defined and (status.stdout == "active" or status.stdout == "inactive")

    roles:
      - kube-controller-manager
