---
  - hosts: master
    any_errors_fatal: true
    name: "Install Kubernetes Scheduler"
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml

    roles:
      - kube-scheduler
