---
  - hosts: master
    any_errors_fatal: true
    name: "{{ play_name | default('Start Kubernetes Controller Manager') }}"
    serial: "{{ serial_count | default('100%') }}"
    become: yes
    vars_files:
      - group_vars/all.yaml

    pre_tasks:
      - name: download kube-controller-manager image
        command: docker pull {{ kube_controller_manager_img }}
        register: result
        until: result|succeeded
        retries: 2
        delay: 1

    roles:
      - kube-controller-manager
