---
  - hosts: master:worker:ingress:storage
    any_errors_fatal: true
    name: "{{ play_name | default('Start Kubernetes Kubelet') }}"
    serial: "{{ serial_count | default('100%') }}"
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml
    roles:
      - role: packages-kubernetes
        when: allow_package_installation|bool == true
      - kubelet
