---
  - hosts: master:worker:ingress:storage
    any_errors_fatal: true
    name: Generate Kubectl Config File
    serial: "{{ serial_count | default('100%') }}"
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml

    roles:
      - kubeconfig
