---
  - hosts: master:worker:ingress:storage
    any_errors_fatal: true
    name: "Start Kubernetes Kubelet"
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml
    roles:
      - kubelet
