---
  - hosts: worker
    any_errors_fatal: true
    name: "Install Kubernetes Kubelet on Worker Nodes"
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml
    vars:
      - kubernetes_schedulable: true

    roles:
      - kubeconfig
      - kubelet
