---
  - hosts: master
    any_errors_fatal: true
    name: "{{ play_name | default('Start Kubernetes API Server') }}"
    serial: "{{ serial_count | default('100%') }}"
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml

    roles:
      - authorization-policy
      - kube-apiserver
