---
  # update hosts files of all nodes
  - hosts: all
    any_errors_fatal: true
    name: "Configure Kismatic Package Repos"
    remote_user: root
    become_method: sudo

    roles:
      - role: packages-repo
        when: >
              disconnected_installation|bool != true and
              ((package_repository_urls is undefined) or
              (package_repository_urls is defined and package_repository_urls == ""))
      - role: packages-repo-custom
        when: package_repository_urls is defined and package_repository_urls != ""
