---
  # update hosts files of all nodes
  - hosts: all
    any_errors_fatal: true
    name: "Configure Kismatic Package Repos"
    remote_user: root
    become_method: sudo

    roles:
      - role: packages-repo
