---
  - hosts: master
    any_errors_fatal: true
    name: "Smoke test Master Nodes"
    remote_user: root
    become_method: sudo
    serial: 1
    vars_files:
      - group_vars/all.yaml

    roles:
      - smoketest
