---
  - hosts: master[0]
    any_errors_fatal: true
    name: "Validate Kubernetes Controlplane is Running"
    remote_user: root
    become_method: sudo
    run_once: true

    roles:
      - validate-controlplane
