---
  - hosts: master
    any_errors_fatal: true
    name: "Validate Kubernetes Control Plane is Running"
    serial: "{{ serial_count | default('1') }}"
    remote_user: root
    become_method: sudo
    run_once: true

    roles:
      - validate-control-plane-node
