---
  - include: _all.yaml
  - include: _hosts.yaml
    when: modify_hosts_file|bool == true
  - include: _certs.yaml
  - include: _kube-config.yaml
  - include: _packages-repo.yaml
    when: allow_package_installation|bool == true
  - include: _docker.yaml
  - include: _kubelet.yaml
  - include: _kube-proxy.yaml
  - include: _calico.yaml
  - include: _calico-validate.yaml
  - include: _update-version.yaml
  - include: _worker-smoke-test.yaml
