---
    # TODO: Is this OK???
  - include: _packages.yaml
    when: allow_package_installation|bool == true

  - name: Upgrade Kubernetes Etcd Cluster
    hosts: etcd
    serial: 1
    any_errors_fatal: true
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml
      - group_vars/etcd-k8s.yaml
    roles:
      - etcd

  - name: Upgrade Networking Etcd Cluster
    hosts: etcd
    serial: 1
    any_errors_fatal: true
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml
      - group_vars/etcd-networking.yaml
    roles:
      - etcd-cert
      - etcd

  - name: Upgrade Kubernetes API Server
    hosts: master
    serial: 1
    any_errors_fatal: true
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml
    roles:
      - authorization-policy
      - apiserver

  - name: Upgrade Kubernetes Scheduler
    hosts: master
    serial: 1
    any_errors_fatal: true
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml
    roles:
      - kubeconfig
      - scheduler

  - name: Upgrade Kubernetes Controller Manager
    hosts: master
    serial: 1
    any_errors_fatal: true
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml
    roles:
      - kubeconfig
      - controller-manager

  - name: Upgrade Docker
    hosts: master:worker:ingress:storage
    any_errors_fatal: true
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml
    roles:
      - role: docker
      - role: docker-registry-cert
        when: use_private_docker_registry is defined and use_private_docker_registry|bool == true

  - name: Upgrade Cluster Network
    hosts: master:worker:ingress:storage
    any_errors_fatal: true
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml
    roles:
      - kubeconfig
      - calico

  - name: Upgrade Kubelet
    hosts: master:worker:ingress:storage
    serial: 1
    any_errors_fatal: true
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml
    roles:
      - kubeconfig
      - kubelet

  - name: Upgrade Kubernetes Proxy
    hosts: master:worker:ingress:storage
    serial: 1
    any_errors_fatal: true
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml
    roles:
      - kubeconfig
      - proxy

  - include: _update-version.yaml