---
  - name: Upgrade Internal Docker Registry
    hosts: master[0]
    remote_user: root
    become_method: sudo
    roles:
      - role: docker-registry-container

  - name: Load Docker Images Into Private Registry
    hosts: master[0]
    remote_user: root
    become_method: sudo
    run_once: true
    roles:
      - role: docker-registry-images