---
  - name: Upgrade Internal Docker Registry
    hosts: master[0]
    remote_user: root
    become_method: sudo
    roles:
      - role: docker-registry-container

  - include: _docker-registry-images.yaml
    when: use_private_docker_registry|bool == true and disconnected_installation|bool == true # only load images if offline