---
  - name: check if docker deamon is already installed
    command: docker ps
    register: docker_ps
    ignore_errors: yes # dont fail, next task will start it if not running

  # YUM
  - name: install docker-engine yum package
    yum: name=docker-engine-{{ docker_engine_yum_version }} state=present
    register: docker_installation_rpm
    until: docker_installation_rpm|success
    retries: 3
    delay: 3
    when: ansible_os_family == 'RedHat' and docker_ps|failed

  # DEB
  - name: install docker-engine deb package
    apt:
      name: docker-engine={{ docker_engine_apt_version }}
      state: present
      default_release: kismatic-xenial
    register: docker_installation_deb
    until: docker_installation_deb|success
    retries: 3
    delay: 3
    when: ansible_os_family == 'Debian' and docker_ps|failed
