---
  # YUM
  - name: install docker-engine yum package
    yum: name=docker-engine-{{ docker_engine_yum_version }} state=present
    register: docker_installation_rpm
    until: docker_installation_rpm|success
    retries: 3
    delay: 3
    when: ansible_os_family == 'RedHat'

  # DEB
  - name: install docker-engine deb package
    apt:
      name: docker-engine={{ docker_engine_apt_version }}
      state: present
      default_release: kismatic-xenial
    register: docker_installation_deb
    until: docker_installation_deb|success
    retries: 3
    delay: 3
    when: ansible_os_family == 'Debian'
