---
  # YUM
  - name: install kismatic offline yum package
    yum: name=kismatic-offline-{{ kismatic_yum_version }} state=present
    register: kismatic_offline_installation_rpm
    until: kismatic_offline_installation_rpm|success
    retries: 3
    delay: 3
    when: "ansible_os_family == 'RedHat' and inventory_hostname == groups['master'][0]"

  # DEB
  - name: install kismatic offline deb package
    apt: name=kismatic-offline={{ kismatic_apt_version }} state=present
    register: kismatic_offline_installation_deb
    until: kismatic_offline_installation_deb|success
    retries: 3
    delay: 3
    when: "ansible_os_family == 'Debian' and inventory_hostname == groups['master'][0]"
