apiVersion: v1
kind: Pod
metadata:
  name: rescheduler
  namespace: kube-system
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
  labels:
    k8s-app: rescheduler
    rescheduler_component_version: "{{ official_images.rescheduler.version }}"
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Rescheduler"
spec:
  hostNetwork: true
  containers:
  - image: {{ images.rescheduler }}
    name: rescheduler
    volumeMounts:
    # TODO: Make resource requirements depend on the size of the cluster
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
    command:
    - /rescheduler 
    - --running-in-cluster=false
