---
  - name: create block directory
    file:
      path: "{{ volume_base_dir }}/{{ volume_name }}"
      state: directory
      mode: "{{ volume_mode }}"

  - name: gluster volume create
    command: gluster volume create {{ volume_name }} replica {{ volume_replica_count }} {% for host in groups['storage'] %} {{ hostvars[host]['inventory_hostname'] }}:/data/{{ volume_name }}{% endfor %} force
    run_once: true
    ignore_errors: yes  #TODO figure out a better way

  - name: gluster volume start
    command: gluster volume start {{ volume_name }}
    run_once: true
    ignore_errors: yes  #TODO figure out a better way

  - name: gluster volume quota enable
    command: gluster volume quota {{ volume_name }} enable
    run_once: true
    ignore_errors: yes  #TODO figure out a better way

  - name: gluster volume quota set
    command: gluster volume quota {{ volume_name }} limit-usage / {{ volume_quota }}
    run_once: true
    ignore_errors: yes  #TODO figure out a better way

  - name: gluster volume quota enable df reporting
    command: gluster volume set {{ volume_name }} quota-deem-statfs on
    run_once: true
    ignore_errors: yes  #TODO figure out a better way

  - name: gluster volume enable nfs
    command: gluster volume set {{ volume_name }} nfs.disable off
    run_once: true
    ignore_errors: yes  #TODO figure out a better way
